### ISSUE TITLE
scenario_runner.py: IndexError: attribute 'role_name' not found

### ISSUE THREAD

**Issue by PetervdPerk** [carla-simulator/scenario_runner#10]
Running Carla 0.9.1 in docker instance
docker run -p 2000-2002:2000-2002 --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0 carlasim/carla:0.9.1 /bin/bash CarlaUE4.sh /Game/Carla/Maps/Town01

Running scenario_runner in a virtualenv  
With PythonAPI version carla-0.9.1-py2.7-linux-x86_64.egg

When I want to test the FollowLeadingVehicle scenario I get the following error.
`(carla_scenario_runner) peter@alienware:~/Carla/scenario_runner$ python scenario_runner.py --scenario FollowLeadingVehicle
Traceback (most recent call last):
  File "scenario_runner.py", line 134, in <module>
    main(args)
  File "scenario_runner.py", line 80, in main
    scenario = scenario_class(world, args.debug)
  File "/home/peter/Carla/scenario_runner/Scenarios/follow_leading_vehicle.py", line 68, in __init__
    self.other_vehicle_start)]
  File "/home/peter/Carla/scenario_runner/Scenarios/basic_scenario.py", line 32, in setup_vehicle
    blueprint.set_attribute('role_name', 'scenario')
IndexError: attribute 'role_name' not found`

Unfortunately I do not have clue what this might cause since manual_control.py seems to be working which is also using the attribute role_name but does not seem to get this error. Has the current master 662bfef been tested with Carla 0.9.1?

**Comment by fabianoboril** [comment]
The current master requires to use the master of Carla (at least commit bc5a3ed), as stated in:
https://github.com/carla-simulator/scenario_runner/commit/faaa70b4da5da41da190c7f6dac35075647ac915
Until our next release the best option is to build Carla from source, when you want to run the scenarios.

Best regards.
