### ISSUE TITLE
did not match C++ signature:

### ISSUE THREAD

**Issue by Donghu1876** [carla-simulator/scenario_runner#1029]
**Describe the bug**
Dear expert,
I have met this error, thanks very much.

**To Reproduce**
1. Running the RL in carla.
2. See error
Traceback (most recent call last):
  File "train_leftturn.py", line 262, in <module>
    train_leftturn_task()
  File "train_leftturn.py", line 88, in train_leftturn_task
    observation = env.reset()
  File "/home/hu/dong/01github/Prioritized-Human-in-the-loop-End-to-end-Autonomous-Driving/env_leftturn.py", line 168, in reset
    self.agent.set_destination((120, 330, spawn_point_ego.location.z))
  File "/home/hu/carla/PythonAPI/carla/agents/navigation/basic_agent.py", line 159, in set_destination
    end_waypoint = self._map.get_waypoint(end_location)
Boost.Python.ArgumentError: Python argument types in
    Map.get_waypoint(Map, tuple)
did not match C++ signature:
    get_waypoint(carla::client::Map {lvalue}, carla::geom::Location location, bool project_to_road=True, int lane_type=carla.libcarla.LaneType.Driving)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - CARLA Version [e.g. CARLA 0.9.14]
 - Python version [e.g. 3.7]
 - UE Version [e.g. 4.26]

**Additional context**

**Comment by AOOOOOA** [comment]
Hi have you solved it?
