### ISSUE TITLE
Log Manager crashes on LOG_ERROR

### ISSUE THREAD

**Issue by haabe** [carla-simulator/scenario_runner#1038]
**Describe the bug**
When parsing a OpenScenario2 file, it sometimes crashes on line 144: `run_log_msg = "[Error]" + " line " + str(line) + ":" + str(column) + ", " + msg` with `TypeError: can only concatenate str (not "NoneType") to str` 

**To Reproduce**
1. Execute ScenarioRunner with a OpenScenario2.0 file containing errors, and also imports another osc file containing errors.

**Expected behavior**
Handling variables properly, so that NoneType won't occur

```cmd
D:\clean\scenario_runner>python scenario_runner.py --openscenario2 examples\Town15_t6.osc
[Error] file "D:\clean\scenario_runner/osc.standard", line 764:27, no viable alternative at input 'it==actor'
SyntaxError: invalid syntax
[Error] file "D:\clean\scenario_runner/osc.standard", line 776:27, no viable alternative at input 'it==actor'
SyntaxError: invalid syntax
[Error] file "D:\clean\scenario_runner/osc.standard", line 809:27, no viable alternative at input 'it==actor'
SyntaxError: invalid syntax
[Error] file "D:\clean\scenario_runner/osc.standard", line 821:27, no viable alternative at input 'it==actor'
SyntaxError: invalid syntax
[Error] file "D:\clean\scenario_runner/osc.standard", line 850:27, no viable alternative at input 'it==actor'
SyntaxError: invalid syntax
[Error] file "D:\clean\scenario_runner/osc.standard", line 1021:8, '        '
SyntaxError: invalid syntax
[Error] file "D:\clean\scenario_runner/osc.standard", line 1023:4, 'at'
SyntaxError: invalid syntax
[Error] file "D:\clean\scenario_runner/osc.standard", line 1024:8, '        '
SyntaxError: invalid syntax
[Error] file "D:\clean\scenario_runner/osc.standard", line 1024:4, ' '
SyntaxError: invalid syntax
[Error] file "D:\clean\scenario_runner/osc.standard", line 1026:8, '        '
SyntaxError: invalid syntax
[Error] file "D:\clean\scenario_runner/osc.standard", line 1026:4, ' '
SyntaxError: invalid syntax
[Error] file "D:\clean\scenario_runner/osc.standard", line 1028:8, '        '
SyntaxError: invalid syntax
[Error] file "D:\clean\scenario_runner/osc.standard", line 1028:4, ' '
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "scenario_runner.py", line 637, in main
    result = scenario_runner.run()
  File "scenario_runner.py", line 537, in run
    result = self._run_osc2()
  File "scenario_runner.py", line 520, in _run_osc2
    config = OSC2ScenarioConfiguration(self._args.openscenario2, self.client)
  File "D:\clean\scenario_runner\srunner\scenarioconfigs\osc2_scenario_configuration.py", line 48, in __init__
    self.ast_tree = OSC2Helper.gen_osc2_ast(self.filename)
  File "D:\clean\scenario_runner\srunner\tools\osc2_helper.py", line 47, in gen_osc2_ast
    parse_tree = parser.osc_file()
  File "D:\clean\scenario_runner\srunner\osc2\osc2_parser\OpenSCENARIO2Parser.py", line 11895, in osc_file
    self._errHandler.sync(self)
  File "C:\Users\Way\AppData\Roaming\Python\Python38\site-packages\antlr4\error\ErrorStrategy.py", line 234, in sync
    self.reportUnwantedToken(recognizer)
  File "C:\Users\Way\AppData\Roaming\Python\Python38\site-packages\antlr4\error\ErrorStrategy.py", line 318, in reportUnwantedToken
    recognizer.notifyErrorListeners(msg, t, None)
  File "C:\Users\Way\AppData\Roaming\Python\Python38\site-packages\antlr4\Parser.py", line 322, in notifyErrorListeners
    listener.syntaxError(self, offendingToken, line, column, msg, e)
  File "C:\Users\Way\AppData\Roaming\Python\Python38\site-packages\antlr4\error\ErrorListener.py", line 60, in syntaxError
    delegate.syntaxError(recognizer, offendingSymbol, line, column, msg, e)
  File "D:\clean\scenario_runner\srunner\osc2\error_manager\error_listener.py", line 55, in syntaxError
    self.reportIndentationError(line, column, None)
  File "D:\clean\scenario_runner\srunner\osc2\error_manager\error_listener.py", line 32, in reportIndentationError
    LOG_ERROR(token_name, line=line, column=column)
  File "D:\clean\scenario_runner\srunner\osc2\utils\log_manager.py", line 145, in LOG_ERROR
    run_log_msg = "[Error]" + " line " + str(line) + ":" + str(column) + ", " + msg
TypeError: can only concatenate str (not "NoneType") to str
```

Adding an extra check for NoneType after setting file_path and line does solve it:
Line 142 through 155:
```python
    elif line is not None and column is not None:
        file_path, line = import_msg.get_msg(line)
        if line is not None and column is not None and file_path is not None and msg is not None:
            run_log_msg = "[Error]" + " line " + str(line) + ":" + str(column) + ", " + msg
            msg = (
                '[Error] file "'
                + file_path
                + '", line '
                + str(line)
                + ":"
                + str(column)
                + ", "
                + msg
            )
```

**Comment by Wang-Zhewei** [comment]
I want to use scenario runner to run the Openscenario2 file exported from RoadRunner Scenario. How can I obtain the osc.standard file?

**Comment by hsiang-lee** [comment]
https://osc2studio.online
