### ISSUE TITLE
There is a problem with the OpenScenario scene file .xosc exported by 51Sim-one software! !

### ISSUE THREAD

**Issue by Xiaowuzjj** [carla-simulator/scenario_runner#1108]
python scenario_runner.py --openscenario srunner/examples/test2.xosc

Traceback (most recent call last):
  File "/home/uu/CARLA/CARLA_0.9.14/scenario_runner/scenario_runner.py", line 651, in main
    result = scenario_runner.run()
  File "/home/uu/CARLA/CARLA_0.9.14/scenario_runner/scenario_runner.py", line 545, in run
    result = self._run_openscenario()
  File "/home/uu/CARLA/CARLA_0.9.14/scenario_runner/scenario_runner.py", line 515, in _run_openscenario
    config = OpenScenarioConfiguration(self._args.openscenario, self.client, openscenario_params)
  File "/home/uu/CARLA/CARLA_0.9.14/scenario_runner/srunner/scenarioconfigs/openscenario_configuration.py", line 63, in __init__
    self._parse_openscenario_configuration()
  File "/home/uu/CARLA/CARLA_0.9.14/scenario_runner/srunner/scenarioconfigs/openscenario_configuration.py", line 91, in _parse_openscenario_configuration
    self._check_version()
  File "/home/uu/CARLA/CARLA_0.9.14/scenario_runner/srunner/scenarioconfigs/openscenario_configuration.py", line 106, in _check_version
    raise AttributeError("Only OpenSCENARIO 1.0 is supported")
AttributeError: Only OpenSCENARIO 1.0 is supported

**Comment by starrye** [comment]
Change your xosc by adding a line above `<ParameterDeclarations/>`, `<FileHeader revMajor="1" revMinor="0" date="2024-05-20T10:00:00" description=“xxe" author="xx."/>` or Comment out this line`self._check_version()`
