### ISSUE TITLE
import carla error: undefined symbol: PyString_Type

### ISSUE THREAD

**Issue by zwbai** [carla-simulator/scenario_runner#298]
Hi, after following the tutorial at [https://carla.readthedocs.io/en/latest/how_to_build_on_linux/](url). I want to run the tutorial.py to test the environment. But there is the problem:
`michael@michael:~$ python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import carla
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/michael/.local/lib/python3.5/site-packages/carla-0.9.5-py2.7-linux-x86_64.egg/carla/__init__.py", line 8, in <module>
  File "/home/michael/.local/lib/python3.5/site-packages/carla-0.9.5-py2.7-linux-x86_64.egg/carla/libcarla.py", line 7, in <module>
  File "/home/michael/.local/lib/python3.5/site-packages/carla-0.9.5-py2.7-linux-x86_64.egg/carla/libcarla.py", line 6, in __bootstrap__
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/michael/.cache/Python-Eggs/carla-0.9.5-py2.7-linux-x86_64.egg-tmp/carla/libcarla.so: undefined symbol: PyString_Type
>>> 
`
Does anyone knows how to solve this problem? thanks.

**Comment by zwbai** [comment]
I also changed the egg file installation but there is still the problem. 
![PyString](https://user-images.githubusercontent.com/23632221/59633989-98bd0f80-9102-11e9-829c-f7a33dacf513.png)
