### ISSUE TITLE
ERROR: 'Vehicle' object has no attribute 'get_control'

### ISSUE THREAD

**Issue by GetDarren** [carla-simulator/scenario_runner#36]
```
(carla) cienet@cienet-desktop:~/scenario_runner$ python scenario_runner.py --scenario FollowLeadingVehicle
Preparing scenario: FollowLeadingVehicle
ScenarioManager: Running scenario FollowVehiclcd
```

And then I start a new terminal,  try to run the manual_control.py

but I met an error like this:
```

ERROR: 'Vehicle' object has no attribute 'get_control'
Traceback (most recent call last):
  File "manual_control.py", line 681, in main
    game_loop(args)
  File "manual_control.py", line 622, in game_loop
    if not world.tick(clock):
  File "manual_control.py", line 162, in tick
    self.hud.tick(self, clock)
  File "manual_control.py", line 281, in tick
    c = world.vehicle.get_control()
AttributeError: 'Vehicle' object has no attribute 'get_control'
```

my friend and I have the same version of packages, but it works well at his computer.

Please help to have a look.

**Comment by GetDarren** [comment]
> You need to update to the recent CARLA release 0.9.3, which will resolve this issue.

I update the 0.9.3 and then run the "python scenario_runner.py"
There is an import module error:
`Traceback (most recent call last):
  File "scenario_runner.py", line 25, in <module>
    from Scenarios.follow_leading_vehicle import *
  File "/home/cienet/scenario_runner/Scenarios/follow_leading_vehicle.py", line 24, in <module>
    from ScenarioManager.atomic_scenario_behavior import *
  File "/home/cienet/scenario_runner/ScenarioManager/atomic_scenario_behavior.py", line 21, in <module>
    from agents.navigation.basic_agent import *
  File "/home/cienet/CARLA_0.9.3/PythonAPI/agents/navigation/basic_agent.py", line 21, in <module>
    from agents.navigation.global_route_planner import GlobalRoutePlanner
  File "/home/cienet/CARLA_0.9.3/PythonAPI/agents/navigation/global_route_planner.py", line 15, in <module>
    from local_planner import RoadOption
ImportError: No module named 'local_planner'
`

But the 'local_planner.py' is in the same folder with "global_route_planner.py"

Then I commented  " from local_planner import RoadOption"

The scenario_runner.py and manual_control.py  both worked.
