### ISSUE TITLE
Scenario not supported 

### ISSUE THREAD

**Issue by s-rajab** [carla-simulator/scenario_runner#571]
Hi. I tried adding a new scenario by slightly modifying existing one. I followed instruction (created a new class, config file and imported the class in scenario_runner.py)
I tried running the scenario using the following command which was working successfully for other scenarios:

$:~/carla/scenario_runner$ python scenario_runner.py --scenario V2M --reloadWorld --output
Preparing scenario: V2M

I received the following output:
Scenario 'V2M' not supported ... Exiting
Traceback (most recent call last):
  File "scenario_runner.py", line 610, in main
    result = scenario_runner.run()
  File "scenario_runner.py", line 530, in run
    result = self._run_scenarios()
  File "scenario_runner.py", line 434, in _run_scenarios
    result = self._load_and_run_scenario(config)
  File "scenario_runner.py", line 346, in _load_and_run_scenario
    scenario_class = self._get_scenario_class_or_fail(config.type)
  File "scenario_runner.py", line 179, in _get_scenario_class_or_fail
    sys.exit(-1)
SystemExit: -1

**Desktop (please complete the following information):**
 - OS: [Ubuntu 16.04]
 - CARLA Version [CARLA 0.9.7]
 - Python version [3.5]
 - Version [0.9.7]

**Comment by s-rajab** [comment]
The new class needs to be imported properly in scenario_runner.py
