### ISSUE TITLE
RelativeTargetSpeed OSC issue

### ISSUE THREAD

**Issue by sagar-g-v** [carla-simulator/scenario_runner#632]
I was trying to use relative speed in open scenario, but i got the below error.

Traceback (most recent call last):
  File "scenario_runner.py", line 367, in _load_and_run_scenario
    timeout=100000)
  File "/home/harsha/scenario_runner/srunner/scenarios/open_scenario.py", line 188, in __init__
    terminate_on_failure=False, criteria_enable=criteria_enable)
  File "/home/harsha/scenario_runner/srunner/scenarios/basic_scenario.py", line 63, in __init__
    behavior = self._create_behavior()
  File "/home/harsha/scenario_runner/srunner/scenarios/open_scenario.py", line 310, in _create_behavior
    child, joint_actor_list[actor_id], self.config.catalogs)
  File "/home/harsha/scenario_runner/srunner/tools/openscenario_parser.py", line 983, in convert_maneuver_to_atomic
    target_speed,
UnboundLocalError: local variable 'target_speed' referenced before assignment
local variable 'target_speed' referenced before assignment

I was able to fix it from my end, but not sure if it is up to open-scenario standards.

**Desktop:**
 - OS: 18.04
 - CARLA Version: CARLA 0.9.9.4
 - Python version : 2.7
 - Version: 0.9.9

**Comment by ThrashAbaddon** [comment]
@sagar-g-v Could you please submit a PR with what you have?

**Comment by fabianoboril** [comment]
This seems to be included in #638

**Comment by sagar-g-v** [comment]
Yes. I will submit a pull request for this.
