### ISSUE TITLE
manual_control.py uses hard-coded port 8000 for TM 

### ISSUE THREAD

**Issue by Kipt** [carla-simulator/scenario_runner#676]
I'm running several Carla instances through Docker and map the Traffic Manager port, but _manual_control.py_ includes the _manual_control.py_ in the examples folder that uses default port. This causes a runtime error in `KeyboardControl` constructor, `world.player.set_autopilot(self._autopilot_enabled)`.

Steps to reproduce:
1. Run Carla in Docker and don't expose port 8000.
2. Run scenario runner with appropriate `--host`, `--port` and `--trafficManagerPort` arguments.
3. Run scenario runner's `manual_control.py`.

**Expected behavior**
pygame window appearing with a vehicle to control.

**Actual behavior**
Crash with message:
```
Traceback (most recent call last):
  File "manual_control.py", line 220, in main
    game_loop(args)
  File "manual_control.py", line 148, in game_loop
    controller = KeyboardControl(world, args.autopilot)
  File "/home/adam/carla_apis/PythonAPI_v0.9.10/examples/manual_control.py", line 292, in __init__
    world.player.set_autopilot(self._autopilot_enabled)
RuntimeError: trying to create rpc server for traffic manager; but the system failed to create because of bind error.
```

**Comment by glopezdiest** [comment]
Hey @Kipt. That is indeed the case. However, this isn't an SR problem but a CARLA one, as we are only inheriting from that class. I'm moving to the CARLA repository
