### ISSUE TITLE
scenario_runner.py invalid syntax xmlschema

### ISSUE THREAD

**Issue by ourange** [carla-simulator/scenario_runner#743]
I can't run 
python scenario_runner.py --scenario FollowLeadingVehicle_1 --reloadWorld

It shows:
========
Traceback (most recent call last):
  File "scenario_runner.py", line 35, in <module>
    from srunner.scenarioconfigs.openscenario_configuration import OpenScenarioConfiguration
  File "/home/ian/scenario_runner/srunner/scenarioconfigs/openscenario_configuration.py", line 16, in <module>
    import xmlschema
  File "/home/ian/.local/lib/python2.7/site-packages/xmlschema/__init__.py", line 15, in <module>
    from .resources import (
  File "/home/ian/.local/lib/python2.7/site-packages/xmlschema/resources.py", line 14, in <module>
    from elementpath import iter_select, Selector, XPath1Parser
  File "/home/ian/.local/lib/python2.7/site-packages/elementpath/__init__.py", line 23, in <module>
    from . import datatypes
  File "/home/ian/.local/lib/python2.7/site-packages/elementpath/datatypes/__init__.py", line 20, in <module>
    from .atomic_types import xsd10_atomic_types, xsd11_atomic_types, AnyAtomicType
  File "/home/ian/.local/lib/python2.7/site-packages/elementpath/datatypes/atomic_types.py", line 101
    class AnyAtomicType(metaclass=AtomicTypeABCMeta):
                                 ^
SyntaxError: invalid syntax

============
I'm using

carla 0.9.10.1
python 2
scenrario_runner 0.9.10

xmlschema==1.0.18

also the python manual_control.py in scenario_runner works but is waiting for ego

How can I solve the error?

Thank you

**Comment by lsy234009** [comment]
![image](https://user-images.githubusercontent.com/28496006/114846131-f578d680-9e0e-11eb-99f3-5c98e6942491.png)
scenrario_runner 0.9.11
python3 
runs well~ you can change the version to 0.9.11
