### ISSUE TITLE
Scenario runner install error due to networkx package

### ISSUE THREAD

**Issue by kanakab** [carla-simulator/scenario_runner#746]
**Describe our question or idea**
I am trying to install scenario runner. I have downloaded the tar.gz file and extracted for version 0.9.10. I am facing issues when I ran the command:
     pip2 install --user -r requirements.txt  or pip2 install networkx

Error message:
Collecting networkx
Collecting decorator>=4.3.0 (from networkx)
  Using cached https://files.pythonhosted.org/packages/71/bd/042e63027bea950da4e6f5545eb59b973868da854ab30a18128d3b884104/decorator-5.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-VqVqq1/decorator/setup.py", line 4, in <module>
        exec(open('src/decorator.py').read(), dic)  # extract the version
      File "<string>", line 162
        print('Error in generated code:', file=sys.stderr)
                                              ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-VqVqq1/decorator/

**Expected behavior**
I want to run a simple scenario and test whether it is working or not. When I run the command python scenario_runner.py --scenario FollowLeadingVehicle_1 --reloadWorld, it is showing no module named networkx

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - CARLA Version [e.g. CARLA 0.9.10]
 - Python version [e.g. 2.7]
 - Version [e.g. 0.9.10]

**Comment by kanakab** [comment]
I was able to solve this issue by creating a virtual environment for python2 and running the requirements.txt file in this new environment
