### ISSUE TITLE
Scenario cannot be loaded 

### ISSUE THREAD

**Issue by ShrenikaSrinivas** [carla-simulator/scenario_runner#789]
Hello,
I am trying to run OpenSCENARIO example on scenariorunner but ended up with the below error. Also manual_control.py is not displaying any ego vehicle. 

python3.8 scenario_runner.py --openscenario /  opt/V2XSimulation/SimulationPlatform/Carla/scenario_runner/srunner/examples/FollowLeadingVehicle.xosc
Preparing scenario: FollowLeadingVehicle
The scenario cannot be loaded
Traceback (most recent call last):
  File "scenario_runner.py", line 374, in _load_and_run_scenario
    scenario = OpenScenario(world=self.world,
  File "/opt/V2XSimulation/SimulationPlatform/Carla/scenario_runner/srunner/scenarios/open_scenario.py", line 187, in __init__
    super(OpenScenario, self).__init__(self.config.name, ego_vehicles=ego_vehicles, config=config,
  File "/opt/V2XSimulation/SimulationPlatform/Carla/scenario_runner/srunner/scenarios/basic_scenario.py", line 63, in __init__
    behavior = self._create_behavior()
  File "/opt/V2XSimulation/SimulationPlatform/Carla/scenario_runner/srunner/scenarios/open_scenario.py", line 252, in _create_behavior
    stories_behavior = py_trees.composites.Parallel(policy=py_trees.common.ParallelPolicy.SUCCESS_ON_ALL,
AttributeError: type object 'ParallelPolicy' has no attribute 'SUCCESS_ON_ALL'
type object 'ParallelPolicy' has no attribute 'SUCCESS_ON_ALL'
Destroying ego vehicle 869
ERROR: failed to destroy actor 869 : unable to destroy actor: not found 
No more scenarios .... Exiting

**Comment by AJK97** [comment]
Hi,
I have the same issue while trying to run carla ros scenario runner, could you please tell me which version of pytrees needs to be installed?

![image](https://github.com/carla-simulator/scenario_runner/assets/139212442/56e25ae4-9f0b-4f31-9cf6-63126d79e8eb)
