### ISSUE TITLE
Unable to run scenario runner using py 3.7 egg

### ISSUE THREAD

**Issue by werewolfdev** [carla-simulator/scenario_runner#854]
Hi Team, Iam using CARLA 0.9.11 and trying to run scenario runner using py3.7 egg  (Linux machine has Python 3.7.5 installed). I am able to run it using py 2.7 egg but I would like to utilise functionalities of python3 and hence need to shift to py3.7 egg version. The error which I am receiving when trying to scenario runner is presented below :

Traceback (most recent call last):
  File "scenario_runner.py", line 35, in <module>
    from srunner.scenarioconfigs.openscenario_configuration import OpenScenarioConfiguration
  File "/home/schemba/CARLA_0.9.11/scenario_runner/srunner/scenarioconfigs/openscenario_configuration.py", line 16, in <module>
    import xmlschema
  File "/home/schemba/.local/lib/python3.7/site-packages/xmlschema/__init__.py", line 15, in <module>
    from .resources import (
  File "/home/schemba/.local/lib/python3.7/site-packages/xmlschema/resources.py", line 14, in <module>
    from elementpath import iter_select, Selector, XPath1Parser
  File "/home/schemba/.local/lib/python3.7/site-packages/elementpath/__init__.py", line 25, in <module>
    from .xpath_context import XPathContext, XPathSchemaContext
  File "/home/schemba/.local/lib/python3.7/site-packages/elementpath/xpath_context.py", line 15, in <module>
    from .xpath_nodes import AttributeNode, TypedAttribute, TypedElement, is_etree_element, \
  File "/home/schemba/.local/lib/python3.7/site-packages/elementpath/xpath_nodes.py", line 19, in <module>
    from .datatypes import ncname_validator
ImportError: cannot import name 'ncname_validator' from 'elementpath.datatypes' (/home/schemba/.local/lib/python3.7/site-packages/elementpath/datatypes/__init__.py)

Kindly let me know if any further information is required from my end

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - CARLA Version [e.g. CARLA 0.9.11]
 - Python version [2.7,3.7.5]
 - SR Version [e.g. 0.9.11]

**Comment by werewolfdev** [comment]
Thanks for the suggestion. Its solved
