### ISSUE TITLE
Local ParameterDeclaration doesn't work

### ISSUE THREAD

**Issue by morishima0524** [carla-simulator/scenario_runner#865]
Declare parameter in global ParameterDeclarations and in local(in Maneuver) ParameterDeclarations.
Second one is named '%first parameter name%_%any characters%' or '%first parameter name%%any characters%'.
Occur RuntimeError or not worked.
Declare Speed1 and Speed_1 as global, thus are worked.

Declare:
```
<OpenSCENARIO>
 <ParameterDeclarations>
  <ParameterDeclaration name="Speed" value="20"/>
 </ParameterDeclarations>
 <Storyboard>
  <Story>
   <ManeuverGroup>
    <Maneuver>
     <ParameterDeclarations>
      <ParameterDeclaration name="Speed_1" value="10"/><!-- not executable (Runtime error occurred) -->
      <ParameterDeclaration name="Speed1" value="10"/><!-- executable but not expected -->
     </ParameterDeclarations>
```

Usage case 1:
```
<LongitudinalAction>
  <SpeedAction>
    <SpeedActionDynamics dynamicsShape="linear" value="10" dynamicsDimension="distance"/>
    <SpeedActionTarget>
      <AbsoluteTargetSpeed value="$Speed_1"/>
    </SpeedActionTarget>
  </SpeedAction>
</LongitudinalAction>
```
-> Error occurred.
```
[WARN] [1646715327.356719, 3169.702962]: [SC]The scenario cannot be loaded
Traceback (most recent call last):
  File "/home/ubuntu/scenario_runner/scenario_runner.py", line 378, in _load_and_run_scenario
[WARN] [1646715327.359163, 3169.752962]: [SC]timeout=100000)
  File "/home/ubuntu/scenario_runner/srunner/scenarios/open_scenario.py", line 189, in __init__
    terminate_on_failure=False, criteria_enable=criteria_enable)
  File "/home/ubuntu/scenario_runner/srunner/scenarios/basic_scenario.py", line 63, in __init__
    behavior = self._create_behavior()
  File "/home/ubuntu/scenario_runner/srunner/scenarios/open_scenario.py", line 312, in _create_behavior
    child, joint_actor_list[actor_id], joint_actor_list, self.config.catalogs)
  File "/home/ubuntu/scenario_runner/srunner/tools/openscenario_parser.py", line 992, in convert_maneuver_to_atomic
    "AbsoluteTargetSpeed").attrib.get('value', 0))
ValueError: invalid literal for float(): 20_1
invalid literal for float(): 20_1
```

Usage case 2:
```
<LongitudinalAction>
  <SpeedAction>
    <SpeedActionDynamics dynamicsShape="linear" value="10" dynamicsDimension="distance"/>
    <SpeedActionTarget>
      <AbsoluteTargetSpeed value="$Speed1"/>
    </SpeedActionTarget>
  </SpeedAction>
</LongitudinalAction>
```
->Don't change car speed.

Ubuntu 18.04
ScenarioRunner 0.9.11(v0.9.11 tag)
CARLA 0.9.11(source build)

**Comment by sagar-g-v** [comment]
local parameter declaration is not supported yet
