### ISSUE TITLE
Scenario Runner and Carla RSS

### ISSUE THREAD

**Issue by AviBen96** [carla-simulator/scenario_runner#968]
Good afternoon,

I have bee using carla 9.13 and leaderboard for a while? For an implementation I switched to the RSS carla version to use this sensor. Since then leaderboard can not launch and I get this error

========= Preparing RouteScenario_0 (repetition 0) =========

Loading the world

The scenario could not be loaded:

Traceback (most recent call last):
File "/home/avner/CARLA_AUTOWARE_project/carla_RSS/leaderboard/leaderboard/leaderboard_evaluator.py", line 227, in _load_and_run_scenario
self._load_and_wait_for_world(args, config.town)
File "/home/avner/CARLA_AUTOWARE_project/carla_RSS/leaderboard/leaderboard/leaderboard_evaluator.py", line 171, in _load_and_wait_for_world
self.world = self.client.load_world(town)
RuntimeError: map not found

Registering the route statistics
Traceback (most recent call last):
File "/home/avner/CARLA_AUTOWARE_project/carla_RSS/leaderboard/leaderboard/leaderboard_evaluator.py", line 227, in _load_and_run_scenario
self._load_and_wait_for_world(args, config.town)
File "/home/avner/CARLA_AUTOWARE_project/carla_RSS/leaderboard/leaderboard/leaderboard_evaluator.py", line 171, in _load_and_wait_for_world
self.world = self.client.load_world(town)
RuntimeError: map not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/avner/CARLA_AUTOWARE_project/carla_RSS/leaderboard/leaderboard/leaderboard_evaluator.py", line 441, in
main()
File "/home/avner/CARLA_AUTOWARE_project/carla_RSS/leaderboard/leaderboard/leaderboard_evaluator.py", line 435, in main
leaderboard_evaluator.run(arguments)
File "/home/avner/CARLA_AUTOWARE_project/carla_RSS/leaderboard/leaderboard/leaderboard_evaluator.py", line 369, in run
crashed = self._load_and_run_scenario(args, config)
File "/home/avner/CARLA_AUTOWARE_project/carla_RSS/leaderboard/leaderboard/leaderboard_evaluator.py", line 241, in _load_and_run_scenario
self._cleanup()
File "/home/avner/CARLA_AUTOWARE_project/carla_RSS/leaderboard/leaderboard/leaderboard_evaluator.py", line 155, in _cleanup
self.world.tick() # TODO: Make sure all scenario actors have been destroyed
AttributeError: 'LeaderboardEvaluator' object has no attribute 'world'

I tried scenario runner to see if it works and it launches but crashes as soon as a second actor starts moving with this error

leRunningRedLight_1
WARNING: Actor model vehicle.* not available. Using instead vehicle.tesla.model3
ScenarioManager: Running scenario OppositeVehicleJunction
Traceback (most recent call last):
File "scenario_runner.py", line 415, in _load_and_run_scenario
self.manager.run_scenario()
File "/home/avner/CARLA_AUTOWARE_project/carla_RSS/leaderboard/scenario_runner/srunner/scenariomanager/scenario_manager.py", line 136, in run_scenario
self._tick_scenario(timestamp)
File "/home/avner/CARLA_AUTOWARE_project/carla_RSS/leaderboard/scenario_runner/srunner/scenariomanager/scenario_manager.py", line 175, in _tick_scenario
self.scenario_tree.tick_once()
File "/home/avner/.local/lib/python3.8/site-packages/py_trees/behaviour.py", line 158, in tick_once
for unused in self.tick():
File "/home/avner/.local/lib/python3.8/site-packages/py_trees/composites.py", line 578, in tick
for node in child.tick():
File "/home/avner/.local/lib/python3.8/site-packages/py_trees/composites.py", line 494, in tick
for node in child.tick():
File "/home/avner/.local/lib/python3.8/site-packages/py_trees/composites.py", line 494, in tick
for node in child.tick():
File "/home/avner/.local/lib/python3.8/site-packages/py_trees/composites.py", line 578, in tick
for node in child.tick():
File "/home/avner/.local/lib/python3.8/site-packages/py_trees/composites.py", line 494, in tick
for node in child.tick():
File "/home/avner/.local/lib/python3.8/site-packages/py_trees/composites.py", line 578, in tick
for node in child.tick():
File "/home/avner/.local/lib/python3.8/site-packages/py_trees/behaviour.py", line 247, in tick
self.initialise()
File "/home/avner/CARLA_AUTOWARE_project/carla_RSS/leaderboard/scenario_runner/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py", line 2059, in initialise
self._agent = ConstantVelocityAgent(
File "/home/avner/CARLA_AUTOWARE_project/carla_RSS/PythonAPI/carla/agents/navigation/constant_velocity_agent.py", line 35, in init
super().init(vehicle, target_speed, opt_dict=opt_dict, map_inst=map_inst, grp_inst=grp_inst)
TypeError: init() got an unexpected keyword argument 'map_inst'
init() got an unexpected keyword argument 'map_inst'
Destroying ego vehicle 2309
ERROR: failed to destroy actor 2309 : unable to destroy actor: not found
Preparing scenario: OppositeVehicleRunningRedLight_2
WARNING: Actor model vehicle.* not available. Using instead vehicle.tesla.model3
ScenarioManager: Running scenario OppositeVehicleJunction

Any idea what is happening ? I download the zip of Carla RSS from the original repo. Everything seems to work correctly.

Help would be very much appriciated !! Thank you :)

**Comment by Anhar2** [comment]
Hello

have you found the solution?
