### ISSUE TITLE
I cannot start Scenario_Runner by Carla. 

### ISSUE THREAD

**Issue by GhaithNasleh** [carla-simulator/scenario_runner#975]
Hello,

I am trying to get Scenario Runner by Carla to run. 

I use windose and have done all the required steps exactly. 

https://github.com/carla-simulator/scenario_runner/blob/master/Docs/getting_scenariorunner.md

I have also installed all the requirements. 

Unfortunately I get this error message: 

D:\scenario_runner>python scenario_runner.py --scenario FollowLeadingVehicle_1 -reloadWorld
Traceback (most recent call last):
  File "scenario_runner.py", line 35, in <module>
    from srunner.scenarioconfigs.openscenario_configuration import OpenScenarioConfiguration
  File "D:\scenario_runner\srunner\scenarioconfigs\openscenario_configuration.py", line 24, in <module>
    from srunner.tools.openscenario_parser import OpenScenarioParser, ParameterRef
  File "D:\scenario_runner\srunner\tools\openscenario_parser.py", line 26, in <module>
    from srunner.scenariomanager.scenarioatomics.atomic_behaviors import (TrafficLightStateSetter,
  File "D:\scenario_runner\srunner\scenariomanager\scenarioatomics\atomic_behaviors.py", line 33, in <module>
    from agents.navigation.basic_agent import BasicAgent
  File "C:\Users\I010503\AppData\Local\Programs\Python\Python37\lib\site-packages\agents\__init__.py", line 21, in <module>
    from . import algorithms
  File "C:\Users\I010503\AppData\Local\Programs\Python\Python37\lib\site-packages\agents\algorithms\__init__.py", line 21, in <module>
    from .ppo import PPO
  File "C:\Users\I010503\AppData\Local\Programs\Python\Python37\lib\site-packages\agents\algorithms\ppo\__init__.py", line 21, in <module>
    from .ppo import PPO
  File "C:\Users\I010503\AppData\Local\Programs\Python\Python37\lib\site-packages\agents\algorithms\ppo\ppo.py", line 31, in <module>
    from agents.algorithms.ppo import utility
  File "C:\Users\I010503\AppData\Local\Programs\Python\Python37\lib\site-packages\agents\algorithms\ppo\utility.py", line 25, in <module>
    from tensorflow.python.client import device_lib
ImportError: cannot import name 'device_lib' from 'tensorflow.python.client' (unknown location)

Would someone please help me? 

Thanks a lot

**Comment by glopezdiest** [comment]
This isn't really an Scenario Runner issue, as the issue seems to be related with `device_lib` from `tensorflow.python.client`

**Comment by GhaithNasleh** [comment]
Thank you for the answer. 
The problem Scenario Runner does not find Agent folder. 

I just copied Agent folder from Carla into Scenario Runner and it works. 

So the methods can be accessed without error feedback.
